- name: DConfg | Create terminal profile keys
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:"
    state: present
    value:
      - ":7de98b53-3c0d-4173-b899-f1ff4591a039"
      - ":ee046b2a-2692-4079-9aab-40293349711d"
  tags:
    - ansible_no_warning

- name: Dconf | Solarized Terminal profile
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:7de98b53-3c0d-4173-b899-f1ff4591a039/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ gnome_terminal_profiles[':7de98b53-3c0d-4173-b899-f1ff4591a039']['keys'] }}"
  tags:
    - ansible_no_warning

- name: Dconf | Nord Terminal profile
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:ee046b2a-2692-4079-9aab-40293349711d/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ gnome_terminal_profiles[':ee046b2a-2692-4079-9aab-40293349711d']['keys'] }}"
  tags:
    - ansible_no_warning


- name: Dconf | Declare default shell profile
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles/default
    value: "':ee046b2a-2692-4079-9aab-40293349711d'"

- name: Dconf | declare profile list
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles/list
    value:
      - "':7de98b53-3c0d-4173-b899-f1ff4591a039'"
      - "':ee046b2a-2692-4079-9aab-40293349711d'"
