- name: Languages | SDKMan
  become: true
  become_user: becker
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -s "https://get.sdkman.io" | bash
    creates: /home/becker/.sdkman/bin/sdkman-init.sh
    chdir: /home/becker
    executable: /bin/bash
  tags:
    - ansible_no_warning

- name: Languages | NVM
  become: true
  become_user: becker
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    creates: /home/becker/.nvm
    executable: /bin/bash
    chdir: /home/becker
  tags:
    - ansible_no_warning
