---
# tasks file for ansible-role-template
- name: Base
  ansible.builtin.include_tasks: base.yml

- name: Repos
  ansible.builtin.include_tasks: repos.yml

- name: Helm
  ansible.builtin.include_tasks: helm.yml
  when: ensure_helm | bool

- name: Mono
  ansible.builtin.include_tasks: mono.yml
  when: (ensure_mono | bool) and (ansible_distribution_release != "jammy")

- name: Slack
  ansible.builtin.include_tasks: slack.yml
  when: (ensure_slack | bool) and (ansible_architecture == "x86_64")

- name: Charm.sh
  ansible.builtin.include_tasks: charm-sh.yml
  when: ensure_charm_sh | bool
