---
# tasks file for ansible-role-template
- name: Base
  ansible.builtin.include_tasks: base.yml

- name: Repos
  ansible.builtin.include_tasks: repos.yml

- name: Helm
  ansible.builtin.include_tasks: helm.yml
  when: ensure_helm | bool

- name: Mono
  ansible.builtin.include_tasks: mono.yml
  when: (ensure_mono | bool) and (ansible_distribution_release != "jammy")
